### ISSUE TITLE
Safe from POST Manipulation?

### ISSUE THREAD

**Issue by Jameses101** [the94air/simplogin#2]
Hello, I am going to make simplogin as my base for my panel but is it safe from post manipulation?

**Comment by Jameses101** [comment]
And Do I have to use $_SESSION['username']; to echo my username?

**Comment by the94air** [comment]
Hey @Jameses101, It has been a long time since I updated this project. I created Simplogin to make fast, safe and easy auth system to use and let others learn how it work. until now I think I need to update it. so soon i am going to introduce Simplogin 2.
As you see in the route folder I am just using `$_POST` and it is kind of not safe. In `Simplogin 2` we are going to use real router. but other than this any thing is fine.
And for the second question I added `$_SESSION['username'];` so you can know witch username you are logging with. you can remove it if you want.
